Repository UBC-MDS/DSCI-532_2024_10_vanweather, pull requests merged in 2024-04, with the labels that each got.

#26 adding preliminary layout
  src/app.py
Labels: enhancement

#27 Added plot to show temperature change over years
  src/app.py
Labels: enhancement

#35 Made changes in app.py for deployment
  src/app.py
Labels: enhancement

#39 adding kpi, charts, and updating format
  notebooks/chart_code.ipynb
  src/app.py
  src/assets/.DS_Store
  src/assets/app.css
  src/utils/.DS_Store
  src/utils/utils.py
Labels: enhancement

#41 Added new package vega-datasets in requirement.txt
  requirements.txt
Labels: enhancement

#42 Fixing deployment issue because of util.py
  src/app.py
  src/utils.py
Labels: bug

#48 changing typo of kpi
  src/app.py
Labels: bug

#49 Added Readme as per milestone2 requirement
  README.md
Labels: documentation

#50 Fixed typos in Readme
  README.md
  img/demo.gif
Labels: documentation

#57 Added data pipeline automation to use latest date to fetch data
  data/raw/van_weather_pipe.csv
  notebooks/data_extraction.ipynb
  src/callbacks.py
  src/components.py
  src/data.py
  src/requirements.txt
  src/utils/__init__.py
  src/utils/loaddata.py
Labels: enhancement

#59 Changed requirement.txt to remove vega
  src/requirements.txt
Labels: bug

#60 Changed requirement.txt to add openmeteo_requests
  src/requirements.txt
Labels: bug

#61 Fix dependency issues for deployment
  src/callbacks.py
  src/requirements.txt
  src/utils/loaddata.py
Labels: bug

#62 Fixed issue in yearly plot
  src/callbacks.py
  src/utils/__init__.py
  src/utils/utils.py
Labels: bug

#65 making changes re: feedback
  data/raw/van_weather_pipe.csv
  src/assets/app.css
  src/callbacks.py
  src/components.py
  src/utils/utils.py
Labels: enhancement

#78 making changes based on peer reviews
  src/app.py
  src/assets/app.css
  src/components.py
  src/utils/utils.py
Labels: enhancement

#79 Added footer about dashboard, contributors and link to repo
  src/assets/app.css
  src/components.py
Labels: enhancement

#86 Fixed last release badge in footer
  README.md
  src/components.py
Labels: enhancement
